version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foyermsdb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  eureka:
    build:
      context: ./Eureka-server
      dockerfile: Dockerfile
    container_name: eureka
    ports:
      - "8761:8761"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 10s
      timeout: 5s
      retries: 10

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: config-server
    ports:
      - "8400:8400"
    depends_on:
      eureka:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "eureka": {
            "client": {
              "service-url": {
                "defaultZone": "http://eureka:8761/eureka/"
              },
              "register-with-eureka": true,
              "fetch-registry": true
            }
          },
          "spring": {
            "cloud": {
              "config": {
                "server": {
                  "git": {
                    "uri": "https://github.com/chaima000/Projet-ms-config.git",
                    "clone-on-start": true
                  }
                }
              }
            }
          }
        }
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8400/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  foyer-ms:
    build:
      context: ./Foyer-ms
      dockerfile: Dockerfile
    container_name: foyer-ms
    ports:
      - "8100:8100"
    depends_on:
      mysqldb:
        condition: service_healthy
      eureka:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "spring": {
            "config": {
              "import": "optional:configserver:http://config-server:8400"
            }
          }
        }
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8100/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  bloc-ms:
    build:
      context: ./Bloc-ms
      dockerfile: Dockerfile
    container_name: bloc-ms
    ports:
      - "8200:8200"
    depends_on:
      mongodb:
        condition: service_healthy
      eureka:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "spring": {
            "config": {
              "import": "optional:configserver:http://config-server:8400"
            }
          }
        }
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data:
  mongo_data:
